import Foundation

/// Curated list of breeds + mixed options seeded into the `breeds` Firestore
/// collection on first app launch (or via a Firebase admin script).
///
/// Usage: iterate `BreedSeed.all` and write each entry to `breeds/{id}`.
/// The `id` values are stable slugs so the seed is idempotent.
enum BreedSeed {

    struct Entry {
        let id: String      // stable slug used as Firestore document ID
        let name: String
        let isActive: Bool
    }

    // MARK: - Seed list

    static let all: [Entry] = purebreds + mixedBreeds

    // MARK: - Purebreds (alphabetical)

    private static let purebreds: [Entry] = [
        Entry(id: "affenpinscher",                name: "Affenpinscher",                  isActive: true),
        Entry(id: "afghan-hound",                 name: "Afghan Hound",                   isActive: true),
        Entry(id: "airedale-terrier",             name: "Airedale Terrier",               isActive: true),
        Entry(id: "akita",                        name: "Akita",                          isActive: true),
        Entry(id: "alaskan-malamute",             name: "Alaskan Malamute",               isActive: true),
        Entry(id: "american-english-coonhound",   name: "American English Coonhound",     isActive: true),
        Entry(id: "american-eskimo-dog",          name: "American Eskimo Dog",            isActive: true),
        Entry(id: "american-foxhound",            name: "American Foxhound",              isActive: true),
        Entry(id: "american-hairless-terrier",    name: "American Hairless Terrier",      isActive: true),
        Entry(id: "american-staffordshire",       name: "American Staffordshire Terrier", isActive: true),
        Entry(id: "american-water-spaniel",       name: "American Water Spaniel",         isActive: true),
        Entry(id: "anatolian-shepherd-dog",       name: "Anatolian Shepherd Dog",         isActive: true),
        Entry(id: "australian-cattle-dog",        name: "Australian Cattle Dog",          isActive: true),
        Entry(id: "australian-shepherd",          name: "Australian Shepherd",            isActive: true),
        Entry(id: "australian-terrier",           name: "Australian Terrier",             isActive: true),
        Entry(id: "azawakh",                      name: "Azawakh",                        isActive: true),
        Entry(id: "barbet",                       name: "Barbet",                         isActive: true),
        Entry(id: "basenji",                      name: "Basenji",                        isActive: true),
        Entry(id: "basset-fauve-de-bretagne",     name: "Basset Fauve de Bretagne",       isActive: true),
        Entry(id: "basset-hound",                 name: "Basset Hound",                   isActive: true),
        Entry(id: "beagle",                       name: "Beagle",                         isActive: true),
        Entry(id: "bearded-collie",               name: "Bearded Collie",                 isActive: true),
        Entry(id: "beauceron",                    name: "Beauceron",                      isActive: true),
        Entry(id: "bedlington-terrier",           name: "Bedlington Terrier",             isActive: true),
        Entry(id: "belgian-laekenois",            name: "Belgian Laekenois",              isActive: true),
        Entry(id: "belgian-malinois",             name: "Belgian Malinois",               isActive: true),
        Entry(id: "belgian-sheepdog",             name: "Belgian Sheepdog",               isActive: true),
        Entry(id: "belgian-tervuren",             name: "Belgian Tervuren",               isActive: true),
        Entry(id: "bergamasco-sheepdog",          name: "Bergamasco Sheepdog",            isActive: true),
        Entry(id: "berger-picard",                name: "Berger Picard",                  isActive: true),
        Entry(id: "bernese-mountain-dog",         name: "Bernese Mountain Dog",           isActive: true),
        Entry(id: "bichon-frise",                 name: "Bichon Frisé",                   isActive: true),
        Entry(id: "biewer-terrier",               name: "Biewer Terrier",                 isActive: true),
        Entry(id: "black-and-tan-coonhound",      name: "Black and Tan Coonhound",        isActive: true),
        Entry(id: "black-russian-terrier",        name: "Black Russian Terrier",          isActive: true),
        Entry(id: "bloodhound",                   name: "Bloodhound",                     isActive: true),
        Entry(id: "bluetick-coonhound",           name: "Bluetick Coonhound",             isActive: true),
        Entry(id: "boerboel",                     name: "Boerboel",                       isActive: true),
        Entry(id: "border-collie",                name: "Border Collie",                  isActive: true),
        Entry(id: "border-terrier",               name: "Border Terrier",                 isActive: true),
        Entry(id: "borzoi",                       name: "Borzoi",                         isActive: true),
        Entry(id: "boston-terrier",                name: "Boston Terrier",                 isActive: true),
        Entry(id: "bouvier-des-flandres",         name: "Bouvier des Flandres",           isActive: true),
        Entry(id: "boxer",                        name: "Boxer",                          isActive: true),
        Entry(id: "boykin-spaniel",               name: "Boykin Spaniel",                 isActive: true),
        Entry(id: "bracco-italiano",              name: "Bracco Italiano",                isActive: true),
        Entry(id: "briard",                       name: "Briard",                         isActive: true),
        Entry(id: "brittany",                     name: "Brittany",                       isActive: true),
        Entry(id: "brussels-griffon",             name: "Brussels Griffon",               isActive: true),
        Entry(id: "bull-terrier",                 name: "Bull Terrier",                   isActive: true),
        Entry(id: "bulldog",                      name: "Bulldog",                        isActive: true),
        Entry(id: "bullmastiff",                  name: "Bullmastiff",                    isActive: true),
        Entry(id: "cairn-terrier",                name: "Cairn Terrier",                  isActive: true),
        Entry(id: "canaan-dog",                   name: "Canaan Dog",                     isActive: true),
        Entry(id: "cane-corso",                   name: "Cane Corso",                     isActive: true),
        Entry(id: "cardigan-welsh-corgi",         name: "Cardigan Welsh Corgi",           isActive: true),
        Entry(id: "cavalier-kcs",                 name: "Cavalier King Charles Spaniel",  isActive: true),
        Entry(id: "cesky-terrier",                name: "Cesky Terrier",                  isActive: true),
        Entry(id: "chesapeake-bay-retriever",     name: "Chesapeake Bay Retriever",       isActive: true),
        Entry(id: "chihuahua",                    name: "Chihuahua",                      isActive: true),
        Entry(id: "chinese-crested",              name: "Chinese Crested",                isActive: true),
        Entry(id: "chinese-shar-pei",             name: "Chinese Shar-Pei",               isActive: true),
        Entry(id: "chinook",                      name: "Chinook",                        isActive: true),
        Entry(id: "chow-chow",                    name: "Chow Chow",                     isActive: true),
        Entry(id: "cirneco-delletna",             name: "Cirneco dell'Etna",              isActive: true),
        Entry(id: "clumber-spaniel",              name: "Clumber Spaniel",                isActive: true),
        Entry(id: "cocker-spaniel",               name: "Cocker Spaniel",                 isActive: true),
        Entry(id: "collie",                       name: "Collie",                         isActive: true),
        Entry(id: "coton-de-tulear",              name: "Coton de Tulear",                isActive: true),
        Entry(id: "curly-coated-retriever",       name: "Curly-Coated Retriever",         isActive: true),
        Entry(id: "dachshund",                    name: "Dachshund",                      isActive: true),
        Entry(id: "dalmatian",                    name: "Dalmatian",                      isActive: true),
        Entry(id: "dandie-dinmont-terrier",       name: "Dandie Dinmont Terrier",         isActive: true),
        Entry(id: "danish-swedish-farmdog",       name: "Danish-Swedish Farmdog",         isActive: true),
        Entry(id: "doberman-pinscher",            name: "Doberman Pinscher",              isActive: true),
        Entry(id: "dogo-argentino",               name: "Dogo Argentino",                 isActive: true),
        Entry(id: "dogue-de-bordeaux",            name: "Dogue de Bordeaux",              isActive: true),
        Entry(id: "english-cocker-spaniel",       name: "English Cocker Spaniel",         isActive: true),
        Entry(id: "english-foxhound",             name: "English Foxhound",               isActive: true),
        Entry(id: "english-setter",               name: "English Setter",                 isActive: true),
        Entry(id: "english-springer-spaniel",     name: "English Springer Spaniel",       isActive: true),
        Entry(id: "english-toy-spaniel",          name: "English Toy Spaniel",            isActive: true),
        Entry(id: "entlebucher-mountain-dog",     name: "Entlebucher Mountain Dog",       isActive: true),
        Entry(id: "field-spaniel",                name: "Field Spaniel",                  isActive: true),
        Entry(id: "finnish-lapphund",             name: "Finnish Lapphund",               isActive: true),
        Entry(id: "finnish-spitz",                name: "Finnish Spitz",                  isActive: true),
        Entry(id: "flat-coated-retriever",        name: "Flat-Coated Retriever",          isActive: true),
        Entry(id: "french-bulldog",               name: "French Bulldog",                 isActive: true),
        Entry(id: "german-pinscher",              name: "German Pinscher",                isActive: true),
        Entry(id: "german-shepherd",              name: "German Shepherd",                isActive: true),
        Entry(id: "german-shorthaired-pointer",   name: "German Shorthaired Pointer",     isActive: true),
        Entry(id: "german-wirehaired-pointer",    name: "German Wirehaired Pointer",      isActive: true),
        Entry(id: "giant-schnauzer",              name: "Giant Schnauzer",                isActive: true),
        Entry(id: "glen-of-imaal-terrier",        name: "Glen of Imaal Terrier",          isActive: true),
        Entry(id: "golden-retriever",             name: "Golden Retriever",               isActive: true),
        Entry(id: "gordon-setter",                name: "Gordon Setter",                  isActive: true),
        Entry(id: "grand-basset-griffon-vendeen", name: "Grand Basset Griffon Vendeen",   isActive: true),
        Entry(id: "great-dane",                   name: "Great Dane",                     isActive: true),
        Entry(id: "great-pyrenees",               name: "Great Pyrenees",                 isActive: true),
        Entry(id: "greater-swiss-mountain-dog",   name: "Greater Swiss Mountain Dog",     isActive: true),
        Entry(id: "greyhound",                    name: "Greyhound",                      isActive: true),
        Entry(id: "harrier",                      name: "Harrier",                        isActive: true),
        Entry(id: "havanese",                     name: "Havanese",                       isActive: true),
        Entry(id: "ibizan-hound",                 name: "Ibizan Hound",                  isActive: true),
        Entry(id: "icelandic-sheepdog",           name: "Icelandic Sheepdog",             isActive: true),
        Entry(id: "irish-red-and-white-setter",   name: "Irish Red and White Setter",     isActive: true),
        Entry(id: "irish-setter",                 name: "Irish Setter",                   isActive: true),
        Entry(id: "irish-terrier",                name: "Irish Terrier",                  isActive: true),
        Entry(id: "irish-water-spaniel",          name: "Irish Water Spaniel",            isActive: true),
        Entry(id: "irish-wolfhound",              name: "Irish Wolfhound",                isActive: true),
        Entry(id: "italian-greyhound",            name: "Italian Greyhound",              isActive: true),
        Entry(id: "jack-russell-terrier",         name: "Jack Russell Terrier",           isActive: true),
        Entry(id: "japanese-chin",                name: "Japanese Chin",                  isActive: true),
        Entry(id: "keeshond",                     name: "Keeshond",                       isActive: true),
        Entry(id: "kerry-blue-terrier",           name: "Kerry Blue Terrier",             isActive: true),
        Entry(id: "komondor",                     name: "Komondor",                       isActive: true),
        Entry(id: "kuvasz",                       name: "Kuvasz",                         isActive: true),
        Entry(id: "labrador-retriever",           name: "Labrador Retriever",             isActive: true),
        Entry(id: "lagotto-romagnolo",            name: "Lagotto Romagnolo",              isActive: true),
        Entry(id: "lakeland-terrier",             name: "Lakeland Terrier",               isActive: true),
        Entry(id: "lancashire-heeler",            name: "Lancashire Heeler",              isActive: true),
        Entry(id: "leonberger",                   name: "Leonberger",                     isActive: true),
        Entry(id: "lhasa-apso",                   name: "Lhasa Apso",                    isActive: true),
        Entry(id: "lowchen",                      name: "Lowchen",                        isActive: true),
        Entry(id: "maltese",                      name: "Maltese",                        isActive: true),
        Entry(id: "manchester-terrier",           name: "Manchester Terrier",             isActive: true),
        Entry(id: "mastiff",                      name: "Mastiff",                        isActive: true),
        Entry(id: "miniature-american-shepherd",  name: "Miniature American Shepherd",    isActive: true),
        Entry(id: "miniature-bull-terrier",       name: "Miniature Bull Terrier",         isActive: true),
        Entry(id: "miniature-pinscher",           name: "Miniature Pinscher",             isActive: true),
        Entry(id: "miniature-schnauzer",          name: "Miniature Schnauzer",            isActive: true),
        Entry(id: "mudi",                         name: "Mudi",                           isActive: true),
        Entry(id: "neapolitan-mastiff",           name: "Neapolitan Mastiff",             isActive: true),
        Entry(id: "nederlandse-kooikerhondje",    name: "Nederlandse Kooikerhondje",      isActive: true),
        Entry(id: "newfoundland",                 name: "Newfoundland",                   isActive: true),
        Entry(id: "norfolk-terrier",              name: "Norfolk Terrier",                isActive: true),
        Entry(id: "norrbottenspets",              name: "Norrbottenspets",                isActive: true),
        Entry(id: "norwegian-buhund",             name: "Norwegian Buhund",               isActive: true),
        Entry(id: "norwegian-elkhound",           name: "Norwegian Elkhound",             isActive: true),
        Entry(id: "norwegian-lundehund",          name: "Norwegian Lundehund",            isActive: true),
        Entry(id: "norwich-terrier",              name: "Norwich Terrier",                isActive: true),
        Entry(id: "nova-scotia-duck-tolling-retriever", name: "Nova Scotia Duck Tolling Retriever", isActive: true),
        Entry(id: "old-english-sheepdog",         name: "Old English Sheepdog",           isActive: true),
        Entry(id: "otterhound",                   name: "Otterhound",                     isActive: true),
        Entry(id: "papillon",                     name: "Papillon",                       isActive: true),
        Entry(id: "parson-russell-terrier",       name: "Parson Russell Terrier",         isActive: true),
        Entry(id: "pekingese",                    name: "Pekingese",                      isActive: true),
        Entry(id: "pembroke-welsh-corgi",         name: "Pembroke Welsh Corgi",           isActive: true),
        Entry(id: "peruvian-inca-orchid",         name: "Peruvian Inca Orchid",           isActive: true),
        Entry(id: "petit-basset-griffon-vendeen", name: "Petit Basset Griffon Vendeen",   isActive: true),
        Entry(id: "pharaoh-hound",                name: "Pharaoh Hound",                  isActive: true),
        Entry(id: "plott-hound",                  name: "Plott Hound",                    isActive: true),
        Entry(id: "pitbull",                      name: "Pitbull",                        isActive: true),
        Entry(id: "pointer",                      name: "Pointer",                        isActive: true),
        Entry(id: "polish-lowland-sheepdog",      name: "Polish Lowland Sheepdog",        isActive: true),
        Entry(id: "pomeranian",                   name: "Pomeranian",                     isActive: true),
        Entry(id: "poodle-miniature",             name: "Poodle (Miniature)",             isActive: true),
        Entry(id: "poodle-standard",              name: "Poodle (Standard)",              isActive: true),
        Entry(id: "poodle-toy",                   name: "Poodle (Toy)",                   isActive: true),
        Entry(id: "portuguese-podengo-pequeno",   name: "Portuguese Podengo Pequeno",     isActive: true),
        Entry(id: "portuguese-water-dog",         name: "Portuguese Water Dog",           isActive: true),
        Entry(id: "pug",                          name: "Pug",                            isActive: true),
        Entry(id: "puli",                         name: "Puli",                           isActive: true),
        Entry(id: "pumi",                         name: "Pumi",                           isActive: true),
        Entry(id: "rat-terrier",                  name: "Rat Terrier",                    isActive: true),
        Entry(id: "redbone-coonhound",            name: "Redbone Coonhound",              isActive: true),
        Entry(id: "rhodesian-ridgeback",          name: "Rhodesian Ridgeback",            isActive: true),
        Entry(id: "rottweiler",                   name: "Rottweiler",                     isActive: true),
        Entry(id: "russell-terrier",              name: "Russell Terrier",                isActive: true),
        Entry(id: "russian-toy",                  name: "Russian Toy",                    isActive: true),
        Entry(id: "russian-tsvetnaya-bolonka",    name: "Russian Tsvetnaya Bolonka",      isActive: true),
        Entry(id: "saint-bernard",                name: "Saint Bernard",                  isActive: true),
        Entry(id: "saluki",                       name: "Saluki",                         isActive: true),
        Entry(id: "samoyed",                      name: "Samoyed",                        isActive: true),
        Entry(id: "schipperke",                   name: "Schipperke",                     isActive: true),
        Entry(id: "scottish-deerhound",           name: "Scottish Deerhound",             isActive: true),
        Entry(id: "scottish-terrier",             name: "Scottish Terrier",               isActive: true),
        Entry(id: "sealyham-terrier",             name: "Sealyham Terrier",               isActive: true),
        Entry(id: "shetland-sheepdog",            name: "Shetland Sheepdog",              isActive: true),
        Entry(id: "shiba-inu",                    name: "Shiba Inu",                      isActive: true),
        Entry(id: "shih-tzu",                     name: "Shih Tzu",                       isActive: true),
        Entry(id: "siberian-husky",               name: "Siberian Husky",                 isActive: true),
        Entry(id: "silky-terrier",                name: "Silky Terrier",                  isActive: true),
        Entry(id: "skye-terrier",                 name: "Skye Terrier",                   isActive: true),
        Entry(id: "sloughi",                      name: "Sloughi",                        isActive: true),
        Entry(id: "smooth-fox-terrier",           name: "Smooth Fox Terrier",             isActive: true),
        Entry(id: "soft-coated-wheaten",          name: "Soft Coated Wheaten Terrier",    isActive: true),
        Entry(id: "spanish-water-dog",            name: "Spanish Water Dog",              isActive: true),
        Entry(id: "spinone-italiano",             name: "Spinone Italiano",               isActive: true),
        Entry(id: "staffordshire-bull-terrier",   name: "Staffordshire Bull Terrier",     isActive: true),
        Entry(id: "standard-schnauzer",           name: "Standard Schnauzer",             isActive: true),
        Entry(id: "sussex-spaniel",               name: "Sussex Spaniel",                 isActive: true),
        Entry(id: "swedish-vallhund",             name: "Swedish Vallhund",               isActive: true),
        Entry(id: "teddy-roosevelt-terrier",      name: "Teddy Roosevelt Terrier",        isActive: true),
        Entry(id: "tibetan-mastiff",              name: "Tibetan Mastiff",                isActive: true),
        Entry(id: "tibetan-spaniel",              name: "Tibetan Spaniel",                isActive: true),
        Entry(id: "tibetan-terrier",              name: "Tibetan Terrier",                isActive: true),
        Entry(id: "toy-fox-terrier",              name: "Toy Fox Terrier",                isActive: true),
        Entry(id: "treeing-walker-coonhound",     name: "Treeing Walker Coonhound",       isActive: true),
        Entry(id: "vizsla",                       name: "Vizsla",                         isActive: true),
        Entry(id: "weimaraner",                   name: "Weimaraner",                     isActive: true),
        Entry(id: "welsh-springer-spaniel",       name: "Welsh Springer Spaniel",         isActive: true),
        Entry(id: "welsh-terrier",                name: "Welsh Terrier",                  isActive: true),
        Entry(id: "west-highland-terrier",        name: "West Highland White Terrier",    isActive: true),
        Entry(id: "whippet",                      name: "Whippet",                        isActive: true),
        Entry(id: "wire-fox-terrier",             name: "Wire Fox Terrier",               isActive: true),
        Entry(id: "wirehaired-pointing-griffon",  name: "Wirehaired Pointing Griffon",    isActive: true),
        Entry(id: "wirehaired-vizsla",            name: "Wirehaired Vizsla",              isActive: true),
        Entry(id: "xoloitzcuintli",               name: "Xoloitzcuintli",                 isActive: true),
        Entry(id: "yorkshire-terrier",            name: "Yorkshire Terrier",              isActive: true),
    ]

    // MARK: - Mixed breeds

    /// High-level mixed options for dogs whose exact breed is unknown or blended.
    /// Listed at the top of the typeahead (sort weight handled client-side).
    private static let mixedBreeds: [Entry] = [
        Entry(id: "mix-general",          name: "Mixed - General",            isActive: true),
        Entry(id: "mix-labrador",         name: "Labrador Mix",               isActive: true),
        Entry(id: "mix-german-shepherd",  name: "German Shepherd Mix",        isActive: true),
        Entry(id: "mix-golden-retriever", name: "Golden Retriever Mix",       isActive: true),
        Entry(id: "mix-poodle",           name: "Poodle Mix",                 isActive: true),
        Entry(id: "mix-beagle",           name: "Beagle Mix",                 isActive: true),
        Entry(id: "mix-husky",            name: "Husky Mix",                  isActive: true),
        Entry(id: "mix-australian-shepherd", name: "Australian Shepherd Mix", isActive: true),
        Entry(id: "mix-border-collie",    name: "Border Collie Mix",          isActive: true),
        Entry(id: "mix-chihuahua",        name: "Chihuahua Mix",              isActive: true),
        Entry(id: "mix-terrier",          name: "Terrier Mix",                isActive: true),
        Entry(id: "mix-hound",            name: "Hound Mix",                  isActive: true),
        Entry(id: "mix-spaniel",          name: "Spaniel Mix",                isActive: true),
        Entry(id: "mix-boxer",            name: "Boxer Mix",                  isActive: true),
        Entry(id: "mix-rottweiler",       name: "Rottweiler Mix",             isActive: true),
    ]
}
